### ISSUE TITLE
tendrl-performance/node-monitoring fails to start after reboot

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/performance-monitoring#104]
Sometimes when machine is rebooted `tendrl-node-monitoring` fails to start.

```
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: etcd.Client(**etcd_kwargs))
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 202, in __init__
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: set(self.machines))
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 304, in machines
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: raise etcd.EtcdException("Could not get the list of servers, "
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[1294]: etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Apr 10 12:47:23 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service failed.
Apr 10 12:47:24 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service holdoff time over, scheduling restart.
Apr 10 12:47:24 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: start request repeated too quickly for tendrl-node-monitoring.service
Apr 10 12:47:24 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Failed to start Daemon to manage tendrl node monitoring.
Apr 10 12:47:24 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
Apr 10 12:47:24 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service failed.
```

Used packages:
tendrl-commons-1.2.2-04_10_2017_04_42_05.noarch
tendrl-node-agent-1.2.2-04_10_2017_00_01_03.noarch
tendrl-node-monitoring-1.2.2-04_10_2017_16_13_14.noarch

**Comment by anmolbabu** [comment]
@ltrilety Can you please confirm that the etcd is running and is accessible using the ip/hostname provided in node-monitoring.conf for etcd_connection.

**Comment by ltrilety** [comment]
@anmolbabu well, it is accessible as restart of the service solve the issue, however when the service tried it first time the connection could be down. That could happen as I didn't fix order of machines to be rebooted and server was restarted too. However one of the machines where the `node`/`performance-monitoring` and `node-agent` failed was the server itself.

**Comment by ltrilety** [comment]
@anmolbabu ok, my bad. So the issue is valid only for the server with `performance-monitoring` instead of `node-monitoring`. Hence I am changing the issue name properly.
The order of starting services is probably wrong because `node-agent` and `performance-monitoring` fail to start. The error message in logs is the same as for `node-monitoring` in Comment 1.

**Comment by ltrilety** [comment]
@anmolbabu I was thinking about the issue and I don't feel it's a correct behavior to fail to start a service when some connection is missing. The service should start and tried regularly if the connection is available.
That said I tried a simple scenario. I shutdown tendrl server and tried to stop/start any tendrl service on any node. Surprisingly it seems to work as it should. Service was started. There was similar etcd error in the log, but service was active and not failed to start. When the connection is available it uses it correctly.
So the issue is related somehow to `etcd` connection, but that's not only think which is bad here.

Example of etcd error in node-monitoring log, when tendrl server is down:
```
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[23668]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 304, in machines
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[23668]: raise etcd.EtcdException("Could not get the list of servers, "
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com tendrl-node-monitoring[23668]: etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service: main process exited, code=exited, status=1/FAILURE
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Unit tendrl-node-monitoring.service entered failed state.
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service failed.
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: tendrl-node-monitoring.service holdoff time over, scheduling restart.
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Started Daemon to manage tendrl node monitoring.
dub 11 12:28:17 ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com systemd[1]: Starting Daemon to manage tendrl node monitoring...
```

**Comment by ltrilety** [comment]
good news is that after some time systemd itself without user intervention was able to start the service

**Comment by r0h4n** [comment]
Fixed: tendrl-performance-monitoring service now Requires tendrl-node-agent which in turn requires the etcd.service

This means, etcd (if installed and configured via systemd) will be always running before any of tendrl services
