### ISSUE TITLE
"Listen 10080" in /etc/tendrl/performance-monitoring/graphite-web.conf.sample causes apache to fail

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/performance-monitoring#118]
In my vagrant env the listen directive causes apache to fail to start. When I remove that line it starts ok. Is it needed?

**Comment by anmolbabu** [comment]
Yes this directive runs graphite-web on 10080. the default port for graphite-web is 80.
But UI also runs on 80 so this directive is needed...

**Comment by anmolbabu** [comment]
Also, it is possible(and I have faced this sometimes) that since we have no selinux in policies in place currently that the port 10080 is not open and hence apache fails to start. So, can you please try this in selinux permissive, iptables flushed and firewalld.

**Comment by nthomas-redhat** [comment]
@japplewhite can you try https://github.com/Tendrl/performance-monitoring/issues/118#issuecomment-296921577 and let us know?

**Comment by r0h4n** [comment]
Any updates?

**Comment by japplewhite** [comment]
Yes - sorry that selinux issue was the problem. Thanks
