### ISSUE TITLE
Re-factor performance monitoring code to extend/use common module

### ISSUE THREAD

**Issue by shtripat** [Tendrl/performance-monitoring#13]
The common module provides all the base classes for flows, atoms, manager, job queue handler, persister and contains all the utilities which are generic in nature like exceptions, command executor, service manager and package installer. The performance_monitoring modules should extend/use these common module changes.

**Comment by r0h4n** [comment]
Any updates? Add spec issue here please

**Comment by shtripat** [comment]
Linked to spec issue https://github.com/Tendrl/specifications/issues/31

Code changes can be done once initial project PR gets merged. Should be assigned to @anmolbabu

**Comment by shtripat** [comment]
@anmolbabu status on this?

**Comment by anmolbabu** [comment]
@shtripat This can be closed but I have no permissions to do the same...

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat This can be closed as it is done....
