### ISSUE TITLE
Periodically store host level monitoring stats and host level alert counter in etcd

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/performance-monitoring#15]
The spec issue is: Tendrl/specifications#81

**Comment by anmolbabu** [comment]
This issue is partially fixed as in stats are available while the alert counter calculation needs to be implemented

**Comment by anmolbabu** [comment]
The alert counter will be made available with https://github.com/Tendrl/performance-monitoring/pull/63/ and https://github.com/Tendrl/alerting/pull/39

**Comment by nthomas-redhat** [comment]
@anmolbabu , is there a fix for this issue?

**Comment by anmolbabu** [comment]
@nthomas-redhat Yes this is implemented I'll close it
