### ISSUE TITLE
Ensure usage of tendrl_context.integration_id is not called cluster_id anywhere

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/performance-monitoring#199]
If `tendrl_context.integration_id` is assumed and used as `cluster_id` , please correct the "cluster_id" term to "integration_id"  since cluster_id is the sds generated (eg: fsid) id

**Comment by r0h4n** [comment]
@anmolbabu when will this be done?

**Comment by anmolbabu** [comment]
PR posted but warrants change in UI
cc @cloudbehl @gnehapk

**Comment by r0h4n** [comment]
@cloudbehl @a2batic @gnehapk Please ensure latest builds of perf-mon/node-mon/alerting work with the UI
