### ISSUE TITLE
Find an better/efficient way to sync per node utilizations

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/performance-monitoring#45]
As in :
https://github.com/Tendrl/performance-monitoring/pull/41/files#diff-02701c14679314952d142d1e276cf1e7R190
currently per node a process is spawned to sync memory, cpu and storage utilizations of the node to etcd. Currently this happens once a minute currently and the processes do get cleaned up, and also considering that each of these per node process would only make 3 http get requests to graphite server and then 1 update to etcd this might not be too very expensive. But this is leading to huge number of defunct processes that show up as defunct for some time until they are cleaned up. This needs to be fixed.

**Comment by nthomas-redhat** [comment]
@anmolbabu please close this issue if fixed
