### ISSUE TITLE
Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/performance-monitoring#64]
There's a lot of `/usr/lib/python2.7/site-packages/urllib3/connectionpool.py - connectionpool.py:272 -            _put_conn() - WARNING - Connection pool is full, discarding connection` lines in `tendrl-performance-monitoring` log. Probably because of that some statistics are missing in graphite.

Used packages:
tendrl-api-doc-1.2.1-03_06_2017_01_51_02.noarch
tendrl-performance-monitoring-1.2.1-03_06_2017_03_02_02.noarch
tendrl-api-1.2.1-03_06_2017_01_51_02.noarch
tendrl-api-httpd-1.2.1-03_06_2017_01_51_02.noarch
tendrl-dashboard-1.2.1-03_06_2017_11_10_12.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-node-agent-1.2.1-03_06_2017_00_01_03.noarch
tendrl-node-monitoring-1.2.1-03_06_2017_00_37_02.noarch
tendrl-gluster-integration-1.2.1-03_05_2017_04_38_02.noarch

**Comment by ltrilety** [comment]
![graphite GUI](https://cloud.githubusercontent.com/assets/22369834/23613141/78c482a4-027e-11e7-8a88-2394162fc9a0.png)

**Comment by anmolbabu** [comment]
@ltrilety This is not the cause for this issue. The stats are pushed to graphite by collectd and performance-monitoring has no role in this. However, performance-monitoring does sync stats from graphite to etcd which is used for stats in GetNodeList api response. It is during this that, the pool full warning appears. However, the urllib3 makes reattempts the requests that could not be made due to pool full, once all the requests in progress are complete . So, effectively there's no impact as such on the functioning of the sync threads and please treat them only as warnings ...

**Comment by ltrilety** [comment]
@anmolbabu ok, thanks for clearing that to me, in that case please look at following screenshot
![hosts_na](https://cloud.githubusercontent.com/assets/22369834/23613985/bf44477a-0281-11e7-989b-a5c8b8182978.png)

I had some performance statistics first but later they disappeared and were replaced with NA. No `stats` for any node in `GetNodeList` response. They were there before.

**Comment by anmolbabu** [comment]
@ltrilety Please attach /var/log/tendrl/performance-monitoring/performance-monitoring_errors.log and /var/log/tendrl/performance-monitoring/performance-monitoring_info.log also the response of http://<ip/hostname_of_machine_where_performance_monitoring_installed>:5000/monitoring/nodes/summary

**Comment by anmolbabu** [comment]
@ltrilety also please provide me the outputs of ps -aux|grep tendrl-performance-monitoring

**Comment by ltrilety** [comment]
`/var/log/tendrl/performance-monitoring/performance-monitoring_errors.log`: empty

`/var/log/tendrl/performance-monitoring/performance-monitoring_info.log`: 
[performance-monitoring_info.tar.gz](https://github.com/Tendrl/performance-monitoring/files/821857/performance-monitoring_info.tar.gz)

`http://ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com:5000/monitoring/nodes/summary`:
```
[
  {
"cpu_usage": {
"percent_used": "12.28",
"updated_at": "2017-03-06T16:55:31.514186"
},
"memory_usage": {
"total": "1929318400.0",
"used": "278134784.0",
"percent_used": "14.42",
"updated_at": "2017-03-06T16:55:31.605491"
},
"storage_usage": {
"total": "2.28200067891e+12",
"percent_used": "0.00455549733007",
"used": "103956480.0",
"updated_at": "2017-03-06T16:56:31.603411"
},
"alert_count": 0,
"node_id": "2fab14d5-595a-4ca8-8c55-19039c085304"
},
  {
"cpu_usage": {
"percent_used": "12.28",
"updated_at": "2017-03-06T16:55:31.514186"
},
"memory_usage": {
"total": "1929318400.0",
"used": "278134784.0",
"percent_used": "14.42",
"updated_at": "2017-03-06T16:55:31.605491"
},
"storage_usage": {
"total": "9.70735242854e+12",
"percent_used": "0.0245746678965",
"used": "103956480.0",
"updated_at": ""
},
"alert_count": 0,
"node_id": "806a2edd-2bc5-405d-bc64-05eb6500bbd9"
},
  {
"cpu_usage": {
"percent_used": "12.28",
"updated_at": "2017-03-06T16:56:31.575312"
},
"memory_usage": {
"total": "1929318400.0",
"used": "278134784.0",
"percent_used": "14.42",
"updated_at": "2017-03-06T16:56:31.654326"
},
"storage_usage": {
"total": "9.70735242854e+12",
"percent_used": "0.0241994894622",
"used": "2349129728.0",
"updated_at": "2017-03-06T16:56:31.774722"
},
"alert_count": 0,
"node_id": "5ce78f66-e69e-4514-80d2-80f0a0db17bc"
},
  {
"cpu_usage": {
"percent_used": "12.15",
"updated_at": "2017-03-06T16:56:31.532214"
},
"memory_usage": {
"total": "1929318400.0",
"used": "274870272.0",
"percent_used": "14.25",
"updated_at": "2017-03-06T16:56:31.650716"
},
"storage_usage": {
"total": "9.70715949466e+12",
"percent_used": "0.0245746678965",
"used": "2385502208.0",
"updated_at": "2017-03-06T16:56:31.738759"
},
"alert_count": 0,
"node_id": "6aaf2950-97b4-4b35-a9a1-ccda379706f6"
}
]
```

**Comment by anmolbabu** [comment]
Looking at response from performance-monitoring API I see no issues @ performance-monitoring end. Please check if GetNodeList API returns response correctly now. If not @anivargi might be able to help.

**Comment by ltrilety** [comment]
Response on `GetNodeList`. There was 'stats' area with performance data for any node, but now that area is missing. 
```
200 OK 157.00 ms
DETAILS
Raw
JSON
 
 
{
"nodes": [
  {
"status": "UP",
"tags": "tendrl/node gluster/server",
"fqdn": "ltrilety-usm1-gl2.usmqe.lab.eng.brq.redhat.com",
"machine_id": "56d65f493d8f854534fe792ecf014b83",
"node_id": "2fab14d5-595a-4ca8-8c55-19039c085304",
"tendrlcontext": {...},
"platform": {...},
"cpu": {...},
"disks": {...},
"os": {...},
"memory": {...}
},
  {
"fqdn": "ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com",
"machine_id": "56d65f493d8f854534fe792ecf014b83",
"node_id": "806a2edd-2bc5-405d-bc64-05eb6500bbd9",
"status": "UP",
"tags": "tendrl/node gluster/server",
"tendrlcontext": {...},
"platform": {...},
"memory": {...},
"os": {...},
"cpu": {...},
"disks": {...},
"detectedcluster": {...}
},
  {
"fqdn": "ltrilety-usm1-gl3.usmqe.lab.eng.brq.redhat.com",
"machine_id": "56d65f493d8f854534fe792ecf014b83",
"node_id": "5ce78f66-e69e-4514-80d2-80f0a0db17bc",
"status": "UP",
"tags": "tendrl/node gluster/server",
"tendrlcontext": {...},
"platform": {...},
"memory": {...},
"disks": {...},
"os": {...},
"cpu": {...}
},
  {
"fqdn": "ltrilety-usm1-gl4.usmqe.lab.eng.brq.redhat.com",
"machine_id": "56d65f493d8f854534fe792ecf014b83",
"node_id": "6aaf2950-97b4-4b35-a9a1-ccda379706f6",
"status": "UP",
"tags": "tendrl/node gluster/server",
"memory": {...},
"disks": {...},
"os": {...},
"cpu": {...},
"tendrlcontext": {...},
"platform": {...}
}
],
"clusters": [
  {
"cluster_id": "76deaff7e1b216c32a4ec107c05d8b3ac8fdbf2ba03d8422a80fc14fb4d20017",
"sds_name": "glusterfs",
"sds_version": "3.9.1",
"node_ids": [
  "806a2edd-2bc5-405d-bc64-05eb6500bbd9"
],
}
],
}
```

**Comment by anmolbabu** [comment]
@anivargi can you please have a look at this

**Comment by ltrilety** [comment]
`stats` are back and graphite seems to have full collection available.

Checked on:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch
