### ISSUE TITLE
yaml content should not be inlined in python source files

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/performance-monitoring#73]
Original issue: Tendrl/commons#201

**Comment by anmolbabu** [comment]
Fix in https://github.com/Tendrl/performance-monitoring/pull/71/files#diff-ba8f61f615f9da72ab3bc45d61434e0cL2
which is part of https://github.com/Tendrl/performance-monitoring/pull/71/

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat Please close this issue as it is fixed as part of #71
