### ISSUE TITLE
Install monitoring pieces on the nodes as part of monitoring configuration flow

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/performance-monitoring#9]
Install monitoring pieces on the nodes as part of monitoring configuration flow

**Comment by anmolbabu** [comment]
Spec Bug: Tendrl/specifications#42

**Comment by nthomas-redhat** [comment]
@anmolbabu I think this is already implemented. Can you confirm?

**Comment by anmolbabu** [comment]
@nthomas-redhat No installation is not done only configuration is there....

**Comment by r0h4n** [comment]
Any ETA on this ?

**Comment by r0h4n** [comment]
@anmolbabu

**Comment by anmolbabu** [comment]
@r0h4n I am currently working on certain issues that are higher on priority than this will work on this once they are done... Regarding ETA I am planning to have this done before End of next week....

**Comment by mbukatov** [comment]
@r0h4n @anmolbabu Is this one considered done or should we keep it open? Do you request additional qe validation for this issue?

**Comment by anmolbabu** [comment]
@mbukatov This is not yet done...

**Comment by r0h4n** [comment]
In light of recent additions like Grafana, we would need to close this issue and re-think the way perf-mon/node-mon would exist as a service
