### ISSUE TITLE
error on RPM update

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/performance-monitoring#95]
performed a yum update today and got this:
(35/38): tendrl-performance-monitoring-1.2.1-04_04_2017_12_41_58.noarch.rpm                                                            |  79 kB  00:00:00
/usr/src/kernels/3.10.0-514.6.2.el7.x86_64/include/config/auto.conf: read error=======================                      ] 3.7 MB/s |  47 MB  00:00:08 ETA
(tried to read 6588 bytes from offset 131112)
cannot reconstruct rpm from disk files

**Comment by r0h4n** [comment]
Is this still valid?

**Comment by TimothyAsir** [comment]
I have verified this. This is bug is fixed and its working now without any issue. We can close this issue.

**Comment by nthomas-redhat** [comment]
Closing the issue as this is already fixed
